name: "AI Code Review"
description: "Automate PR reviews using multiple AI providers with framework-specific expertise; comments only on added lines."
author: "UPDIVISION"
branding:
  icon: "code-review"
  color: "blue"

inputs:
  ai_provider:
    description: "AI provider to use for code review (openai, claude, gemini, deepseek)"
    required: true
  framework:
    description: "Framework for specialized code review (laravel, vue, nuxt, react, nextjs)"
    required: true
  github_token:
    description: "GitHub token for PR access"
    required: true
  
  # OpenAI specific
  openai_api_key:
    description: "OpenAI API key"
    required: false
  openai_assistant_id:
    description: "OpenAI Assistant ID"
    required: false
  
  # Claude specific
  claude_api_key:
    description: "Anthropic Claude API key"
    required: false
  
  # Gemini specific
  gemini_api_key:
    description: "Google Gemini API key"
    required: false
  
  # DeepSeek specific
  deepseek_api_key:
    description: "DeepSeek API key"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ai_provider }}
    - ${{ inputs.framework }}
    - ${{ inputs.github_token }}
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.openai_assistant_id }}
    - ${{ inputs.claude_api_key }}
    - ${{ inputs.gemini_api_key }}
    - ${{ inputs.deepseek_api_key }}
