#!/usr/bin/env bash
set -euo pipefail

AI_PROVIDER="$1"
FRAMEWORK="$2"
GITHUB_TOKEN="$3"
OPENAI_API_KEY="$4"
OPENAI_ASSISTANT_ID="$5"
CLAUDE_API_KEY="$6"
GEMINI_API_KEY="$7"
DEEPSEEK_API_KEY="$8"

export AI_PROVIDER FRAMEWORK GITHUB_TOKEN OPENAI_API_KEY OPENAI_ASSISTANT_ID CLAUDE_API_KEY GEMINI_API_KEY DEEPSEEK_API_KEY

python /action/src/main.py
